import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, test } from "vitest";

const migratedBusinessFiles = [
  "../pages/BookDetailPage.tsx",
  "../pages/BookAiSummaryPage.tsx",
  "../pages/BookshelfPage.tsx",
  "../pages/DiscoveryPage.tsx",
  "../pages/CandidateBookshelfPage.tsx",
  "../components/ReadingAssistantPanel.tsx"
] as const;

const repositoryRoot = fileURLToPath(new URL("../../", import.meta.url));
const retiredUpsertSources = [
  "src/lib/reading-api.ts",
  "src/lib/types.ts",
  "src-tauri/src/commands/reading_state.rs",
  "src-tauri/src/services/reading_state.rs",
  "src-tauri/src/lib.rs",
  "src-tauri/build.rs",
  "src-tauri/capabilities/default.json",
  "tests/e2e/app-smoke.spec.ts"
] as const;

function readSource(relativePath: string): string {
  return readFileSync(fileURLToPath(new URL(relativePath, import.meta.url)), "utf8");
}

describe("T4 reading item upsert retirement", () => {
  test("legacy whole-row upsert API and command stay removed from source and configuration", () => {
    for (const relativePath of retiredUpsertSources) {
      const source = readFileSync(fileURLToPath(new URL(`../../${relativePath}`, import.meta.url)), "utf8");
      expect(source, relativePath).not.toContain("upsertReadingItemState");
      expect(source, relativePath).not.toContain("upsert_reading_item_state");
      expect(source, relativePath).not.toContain("ReadingItemStateInput");
      expect(source, relativePath).not.toContain("allow-upsert-reading-item-state");
    }

    expect(
      existsSync(
        fileURLToPath(
          new URL(
            "../../src-tauri/permissions/autogenerated/upsert_reading_item_state.toml",
            import.meta.url
          )
        )
      )
    ).toBe(false);
  });

  test("patch API, command and legacy read normalizers remain available", () => {
    const readingApi = readFileSync(`${repositoryRoot}/src/lib/reading-api.ts`, "utf8");
    const commandSource = readFileSync(
      `${repositoryRoot}/src-tauri/src/commands/reading_state.rs`,
      "utf8"
    );
    const serviceSource = readFileSync(
      `${repositoryRoot}/src-tauri/src/services/reading_state.rs`,
      "utf8"
    );

    expect(readingApi).toContain("export async function patchReadingItemState");
    expect(readingApi).toContain("function mapReadingItemState");
    expect(commandSource).toContain("pub fn patch_reading_item_state");
    expect(serviceSource).toContain("COALESCE(item_kind");
    expect(serviceSource).toContain("CASE WHEN item_type = 'candidate' AND status = 'toRead'");
    expect(serviceSource).toContain("WHEN 'reviewing' THEN 'to_organize'");
  });
});

describe("T6 book review note-state contracts", () => {
  test("AI review entry shells and dashboard insight entries do not invent note counts", () => {
    const app = readSource("../App.tsx");
    const dashboard = readSource("../pages/DashboardPage.tsx");

    for (const source of [app, dashboard]) {
      expect(source).not.toMatch(/noteCount:\s*1\b/);
      expect(source).not.toMatch(/totalNoteCount:\s*1\b/);
    }
  });

  test("AI review generation waits for real BookNotes instead of fallback counts", () => {
    const summary = readSource("../pages/BookAiSummaryPage.tsx");

    expect(summary).toContain("notesInfo.status === \"ready\"");
    expect(summary).toContain("notesInfo.exportableCount > 0");
    expect(summary).toContain("loadBookNotesOnce(targetBookId)");
    expect(summary).toContain("inFlightBookNotesRequests");
    expect(summary).not.toMatch(/exportableCount\s*\?\?\s*1\b/);
    expect(summary).not.toContain("sourceStatsFromSource");
  });
});

describe("T7 reading selector contracts", () => {
  test("queue selectors remain the single source used by all M1 pages", () => {
    const selector = readSource("../lib/reading-selectors.ts");
    const dashboard = readSource("../pages/DashboardPage.tsx");
    const notes = readSource("../pages/NotesPage.tsx");
    const readingHub = readSource("../pages/ReadingHubPage.tsx");
    const candidateShelf = readSource("../pages/CandidateBookshelfPage.tsx");

    expect(selector).toContain("export function getOrganizeQueue");
    expect(selector).toContain("export function getCandidateQueue");

    for (const [relativePath, source] of [
      ["DashboardPage.tsx", dashboard],
      ["NotesPage.tsx", notes],
      ["ReadingHubPage.tsx", readingHub]
    ] as const) {
      expect(source, relativePath).toContain("getOrganizeQueue({");
      expect(source, relativePath).not.toContain("function getReviewCandidates(");
      expect(source, relativePath).not.toMatch(/calculateTotalNotes\(book\)\s*>\s*0\s*&&\s*!summarizedBookIds/);
    }

    expect(dashboard).toContain("getCandidateQueue(readingStates, 3)");
    expect(candidateShelf).toContain("getCandidateQueue(states)");
    expect(candidateShelf).not.toContain("filter(isSavedCandidateState)");
  });

  test("T7 does not introduce the M2 TodayPlan API", () => {
    const t7Sources = [
      readSource("../lib/reading-selectors.ts"),
      readSource("../pages/DashboardPage.tsx"),
      readSource("../pages/NotesPage.tsx"),
      readSource("../pages/ReadingHubPage.tsx"),
      readSource("../pages/CandidateBookshelfPage.tsx")
    ];

    for (const source of t7Sources) {
      expect(source).not.toContain("getTodayPlan");
      expect(source).not.toContain("get_today_plan");
    }
  });
});

describe("T3 reading item patch contracts", () => {
  test("migrated business files no longer call the legacy whole-row upsert", () => {
    for (const relativePath of migratedBusinessFiles) {
      const source = readSource(relativePath);
      expect(source, relativePath).not.toContain("upsertReadingItemState");
      expect(source, relativePath).toContain("patchReadingItemState");
    }
  });

  test("candidate write paths use structured candidate sources instead of legacy magic notes", () => {
    const bookDetail = readSource("../pages/BookDetailPage.tsx");
    const bookshelf = readSource("../pages/BookshelfPage.tsx");
    const discovery = readSource("../pages/DiscoveryPage.tsx");
    const candidateShelf = readSource("../pages/CandidateBookshelfPage.tsx");
    const assistant = readSource("../components/ReadingAssistantPanel.tsx");

    expect(bookDetail).toContain('candidateSource: "weread"');
    expect(bookDetail).toContain('savedFrom: "book_detail"');
    expect(bookshelf).toContain('candidateSource: "light"');
    expect(discovery).toContain('savedFrom: "discovery"');
    expect(candidateShelf).toContain('candidateSource: "ai_confirmed"');
    expect(candidateShelf).toContain("...(book.sourceMeta ?? {})");
    expect(assistant).toContain('candidateSource: "ai_unconfirmed"');
    expect(assistant).toContain('candidateSource: "ai_confirmed"');
    expect(assistant).toContain("aiReason: book.reason");

    expect(bookDetail).not.toContain("书籍详情页保存的本地候选");
    expect(bookshelf).not.toContain("保存的本地候选`");
    expect(discovery).not.toContain("发现页保存的本地候选");
    expect(assistant).not.toContain("来自 AI 阅读助手微信读书搜索确认。");
  });

  test("organize actions only patch organizeStatus and clearing does not delete the record", () => {
    const bookDetail = readSource("../pages/BookDetailPage.tsx");
    const bookSummary = readSource("../pages/BookAiSummaryPage.tsx");

    expect(bookDetail).toContain(
      '{ organizeStatus: status === "organized" ? "organized" : "to_organize" }'
    );
    expect(bookDetail).toContain('{ organizeStatus: "none" }');
    expect(bookDetail).not.toContain("removeReadingItemState");
    expect(bookSummary).toContain('{ organizeStatus: "organized" }');
  });
});
