import { describe, expect, it } from "vitest";
import { readFileSync, readdirSync } from "node:fs";
import { basename, join } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = fileURLToPath(new URL("../../", import.meta.url));
const tauriRoot = join(repoRoot, "src-tauri");

describe("Tauri command permissions", () => {
  it("keeps runtime, build manifest, generated permissions and capability synchronized", () => {
    const registeredCommands = readRegisteredCommands();
    const manifestCommands = readBuildManifestCommands();
    const permissionCommands = readPermissionFiles();
    const capabilityCommands = readDefaultLocalCapabilityCommands();

    expect(manifestCommands).toEqual(registeredCommands);
    expect(permissionCommands).toEqual(registeredCommands);
    expect(capabilityCommands).toEqual(registeredCommands);
  });

  it("keeps desktop and mobile platform schemas synchronized with every local command", () => {
    const registeredCommands = readRegisteredCommands();

    for (const platform of ["desktop", "windows", "mobile", "android"]) {
      const schemaPermissionIds = readPlatformSchemaPermissionIds(platform);

      for (const command of registeredCommands) {
        const permissionName = command.replace(/_/g, "-");
        expect(schemaPermissionIds, `${platform} schema 缺少 ${command} 的 allow permission`).toContain(
          `allow-${permissionName}`
        );
        expect(schemaPermissionIds, `${platform} schema 缺少 ${command} 的 deny permission`).toContain(
          `deny-${permissionName}`
        );
      }

      expect(schemaPermissionIds).not.toContain("allow-upsert-reading-item-state");
      expect(schemaPermissionIds).not.toContain("deny-upsert-reading-item-state");
    }
  });
});

describe("Tauri window configuration", () => {
  it("uses a roomy desktop default while preserving split-screen minimums", () => {
    const windowConfig = readMainWindowConfig();

    expect(windowConfig.width).toBeGreaterThanOrEqual(1360);
    expect(windowConfig.height).toBeGreaterThanOrEqual(820);
    expect(windowConfig.minWidth).toBe(960);
    expect(windowConfig.minHeight).toBe(640);
    expect(windowConfig.center).toBe(true);
    expect(windowConfig.resizable).toBe(true);
  });

  it("uses an app-owned chrome instead of the native webview title frame", () => {
    const windowConfig = readMainWindowConfig();
    const allowedPermissions = readDefaultCapabilityPermissions();

    expect(windowConfig.decorations).toBe(false);
    for (const permission of [
      "core:window:allow-start-dragging",
      "core:window:allow-minimize",
      "core:window:allow-toggle-maximize",
      "core:window:allow-close"
    ]) {
      expect(allowedPermissions.has(permission)).toBe(true);
    }
  });
});

describe("Tauri Windows packaging", () => {
  it("uses the Windows GUI subsystem for release builds to avoid a console window", () => {
    const mainRs = readFileSync(join(tauriRoot, "src", "main.rs"), "utf8");

    expect(mainRs).toContain('#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]');
  });
});

function readRegisteredCommands(): string[] {
  const libRs = readFileSync(join(tauriRoot, "src", "lib.rs"), "utf8");
  const handlerMatch = libRs.match(/generate_handler!\s*\[\s*([\s\S]*?)\s*\]/);

  if (!handlerMatch) {
    throw new Error("缺少 Tauri generate_handler! 本地命令清单");
  }

  return sortUnique(
    [...handlerMatch[1].matchAll(/commands::[a-z_]+::([a-z_]+)/g)].map((match) => match[1])
  );
}

function readBuildManifestCommands(): string[] {
  const buildRs = readFileSync(join(tauriRoot, "build.rs"), "utf8");
  const commandsMatch = buildRs.match(/\.commands\(&\[([\s\S]*?)\]\)/);

  if (!commandsMatch) {
    throw new Error("缺少 Tauri build.rs 本地命令清单");
  }

  return sortUnique(
    [...commandsMatch[1].matchAll(/"([a-z_]+)"/g)].map((match) => match[1])
  );
}

function readDefaultCapabilityPermissions(): Set<string> {
  const capability = JSON.parse(
    readFileSync(join(tauriRoot, "capabilities", "default.json"), "utf8")
  ) as { permissions?: string[] };

  return new Set(capability.permissions ?? []);
}

function readDefaultLocalCapabilityCommands(): string[] {
  const capability = JSON.parse(
    readFileSync(join(tauriRoot, "capabilities", "default.json"), "utf8")
  ) as { permissions?: string[] };
  const commands = (capability.permissions ?? [])
    .filter((permission) => permission.startsWith("allow-"))
    .map((permission) => permission.slice("allow-".length).replace(/-/g, "_"));

  return sortUnique(commands);
}

function readPermissionFiles(): string[] {
  return sortUnique(
    readdirSync(join(tauriRoot, "permissions", "autogenerated"))
      .filter((fileName) => fileName.endsWith(".toml"))
      .map((fileName) => basename(fileName, ".toml"))
  );
}

function readPlatformSchemaPermissionIds(platform: string): string[] {
  const schema = JSON.parse(
    readFileSync(join(tauriRoot, "gen", "schemas", `${platform}-schema.json`), "utf8")
  ) as unknown;
  const permissionIds = new Set<string>();

  collectPermissionIds(schema, permissionIds);
  return [...permissionIds].sort();
}

function collectPermissionIds(value: unknown, permissionIds: Set<string>) {
  if (typeof value === "string") {
    if (/^(allow|deny)-[a-z0-9-]+$/.test(value)) {
      permissionIds.add(value);
    }
    return;
  }

  if (Array.isArray(value)) {
    for (const item of value) {
      collectPermissionIds(item, permissionIds);
    }
    return;
  }

  if (value && typeof value === "object") {
    for (const item of Object.values(value)) {
      collectPermissionIds(item, permissionIds);
    }
  }
}

function sortUnique(values: string[]): string[] {
  return [...new Set(values)].sort();
}

function readMainWindowConfig() {
  const config = JSON.parse(
    readFileSync(join(tauriRoot, "tauri.conf.json"), "utf8")
  ) as {
    app?: {
      windows?: Array<{
        width?: number;
        height?: number;
        minWidth?: number;
        minHeight?: number;
        center?: boolean;
        resizable?: boolean;
        decorations?: boolean;
      }>;
    };
  };

  const [mainWindow] = config.app?.windows ?? [];

  if (!mainWindow) {
    throw new Error("缺少 Tauri 主窗口配置");
  }

  return mainWindow;
}
