import { describe, expect, it } from "vitest";
import { readFileSync, readdirSync } from "node:fs";
import { basename, join } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = fileURLToPath(new URL("../../", import.meta.url));
const tauriRoot = join(repoRoot, "src-tauri");

describe("Tauri command permissions", () => {
  it("allows every registered local command in the default capability", () => {
    const registeredCommands = readRegisteredCommands();
    const allowedPermissions = readDefaultCapabilityPermissions();
    const permissionFiles = readPermissionFiles();

    const missingPermissions = registeredCommands.filter((command) => {
      const permissionId = `allow-${command.replace(/_/g, "-")}`;
      return !allowedPermissions.has(permissionId) || !permissionFiles.has(command);
    });

    expect(missingPermissions).toEqual([]);
  });
});

describe("Tauri window configuration", () => {
  it("uses a roomy desktop default while preserving split-screen minimums", () => {
    const windowConfig = readMainWindowConfig();

    expect(windowConfig.width).toBeGreaterThanOrEqual(1360);
    expect(windowConfig.height).toBeGreaterThanOrEqual(820);
    expect(windowConfig.minWidth).toBe(960);
    expect(windowConfig.minHeight).toBe(640);
    expect(windowConfig.resizable).toBe(true);
  });

  it("uses an app-owned chrome instead of the native webview title frame", () => {
    const windowConfig = readMainWindowConfig();
    const allowedPermissions = readDefaultCapabilityPermissions();

    expect(windowConfig.decorations).toBe(false);
    for (const permission of [
      "core:window:allow-start-dragging",
      "core:window:allow-minimize",
      "core:window:allow-toggle-maximize",
      "core:window:allow-close"
    ]) {
      expect(allowedPermissions.has(permission)).toBe(true);
    }
  });
});

describe("Tauri Windows packaging", () => {
  it("uses the Windows GUI subsystem for release builds to avoid a console window", () => {
    const mainRs = readFileSync(join(tauriRoot, "src", "main.rs"), "utf8");

    expect(mainRs).toContain('#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]');
  });
});

function readRegisteredCommands(): string[] {
  const libRs = readFileSync(join(tauriRoot, "src", "lib.rs"), "utf8");
  const handlerMatch = libRs.match(/generate_handler!\s*\[\s*([\s\S]*?)\s*\]/);

  if (!handlerMatch) {
    return [];
  }

  return [...handlerMatch[1].matchAll(/commands::[a-z_]+::([a-z_]+)/g)].map((match) => match[1]);
}

function readDefaultCapabilityPermissions(): Set<string> {
  const capability = JSON.parse(
    readFileSync(join(tauriRoot, "capabilities", "default.json"), "utf8")
  ) as { permissions?: string[] };

  return new Set(capability.permissions ?? []);
}

function readPermissionFiles(): Set<string> {
  return new Set(
    readdirSync(join(tauriRoot, "permissions", "autogenerated"))
      .filter((fileName) => fileName.endsWith(".toml"))
      .map((fileName) => basename(fileName, ".toml"))
  );
}

function readMainWindowConfig() {
  const config = JSON.parse(
    readFileSync(join(tauriRoot, "tauri.conf.json"), "utf8")
  ) as {
    app?: {
      windows?: Array<{
        width?: number;
        height?: number;
        minWidth?: number;
        minHeight?: number;
        resizable?: boolean;
        decorations?: boolean;
      }>;
    };
  };

  const [mainWindow] = config.app?.windows ?? [];

  if (!mainWindow) {
    throw new Error("缺少 Tauri 主窗口配置");
  }

  return mainWindow;
}
