use serde::Serialize;
use tauri::AppHandle;

use crate::{
    errors::AppError,
    services::local_books::{
        ImportLocalBookInput, ImportLocalBookResult, LocalBookRecord, LocalBookTextRecord,
        LocalBooksService, LocalReadingProgressRecord, SaveLocalReadingProgressInput,
    },
};

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct AppCommandError {
    code: String,
    message: String,
}

impl From<AppError> for AppCommandError {
    fn from(error: AppError) -> Self {
        Self {
            code: error.code().to_string(),
            message: error.user_message(),
        }
    }
}

#[tauri::command]
pub async fn import_local_book(
    app: AppHandle,
    input: ImportLocalBookInput,
) -> Result<ImportLocalBookResult, AppCommandError> {
    run_blocking(move || LocalBooksService::new(app).import_book(input)).await
}

#[tauri::command]
pub fn choose_local_book_file(app: AppHandle) -> Result<Option<String>, AppCommandError> {
    Ok(pick_local_book_file(&app).map(|path| path.display().to_string()))
}

#[tauri::command]
pub fn list_local_books(app: AppHandle) -> Result<Vec<LocalBookRecord>, AppCommandError> {
    LocalBooksService::new(app).list_books().map_err(Into::into)
}

#[tauri::command]
pub fn get_local_book(
    app: AppHandle,
    book_id: String,
) -> Result<Option<LocalBookRecord>, AppCommandError> {
    LocalBooksService::new(app)
        .get_book(book_id)
        .map_err(Into::into)
}

#[tauri::command]
pub async fn get_local_book_text(
    app: AppHandle,
    book_id: String,
) -> Result<LocalBookTextRecord, AppCommandError> {
    run_blocking(move || LocalBooksService::new(app).get_text(book_id)).await
}

#[tauri::command]
pub fn get_local_reading_progress(
    app: AppHandle,
    book_id: String,
) -> Result<Option<LocalReadingProgressRecord>, AppCommandError> {
    LocalBooksService::new(app)
        .get_progress(book_id)
        .map_err(Into::into)
}

#[tauri::command]
pub fn save_local_reading_progress(
    app: AppHandle,
    input: SaveLocalReadingProgressInput,
) -> Result<LocalReadingProgressRecord, AppCommandError> {
    LocalBooksService::new(app)
        .save_progress(input)
        .map_err(Into::into)
}

#[cfg(not(mobile))]
fn pick_local_book_file(app: &AppHandle) -> Option<std::path::PathBuf> {
    use tauri_plugin_dialog::DialogExt;

    app.dialog()
        .file()
        .set_title("选择本地图书")
        .add_filter("图书文件", &["epub", "txt"])
        .blocking_pick_file()
        .and_then(|path| path.into_path().ok())
}

#[cfg(mobile)]
fn pick_local_book_file(_app: &AppHandle) -> Option<std::path::PathBuf> {
    None
}

async fn run_blocking<T>(
    task: impl FnOnce() -> Result<T, AppError> + Send + 'static,
) -> Result<T, AppCommandError>
where
    T: Send + 'static,
{
    tauri::async_runtime::spawn_blocking(task)
        .await
        .map_err(|error| AppCommandError {
            code: "local_task_failed".to_string(),
            message: format!("本地任务执行失败：{error}"),
        })?
        .map_err(Into::into)
}

#[cfg(test)]
mod tests {
    const LOCAL_BOOK_COMMANDS: &[&str] = &[
        "import_local_book",
        "choose_local_book_file",
        "list_local_books",
        "get_local_book",
        "get_local_book_text",
        "get_local_reading_progress",
        "save_local_reading_progress",
    ];

    #[test]
    fn local_book_commands_are_registered_and_permitted() {
        let manifest_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
        let lib_rs = read_manifest_file(manifest_dir, "src/lib.rs");
        let build_rs = read_manifest_file(manifest_dir, "build.rs");
        let capability = read_manifest_file(manifest_dir, "capabilities/default.json");

        for command in LOCAL_BOOK_COMMANDS {
            assert!(
                lib_rs.contains(&format!("commands::local_books::{command}")),
                "{command} should be registered in tauri invoke_handler"
            );
            assert!(
                build_rs.contains(&format!("\"{command}\"")),
                "{command} should be listed in Tauri build manifest"
            );

            let permission_id = format!("allow-{}", command.replace('_', "-"));
            assert!(
                capability.contains(&format!("\"{permission_id}\"")),
                "{permission_id} should be enabled in default capability"
            );

            let permission_file = manifest_dir
                .join("permissions")
                .join("autogenerated")
                .join(format!("{command}.toml"));
            assert!(
                permission_file.is_file(),
                "{command} should have an autogenerated permission file"
            );

            let permission_text = std::fs::read_to_string(&permission_file)
                .expect("permission file should be readable");
            assert!(
                permission_text.contains(&format!("commands.allow = [\"{command}\"]")),
                "{command} permission should allow the matching command"
            );
        }
    }

    fn read_manifest_file(manifest_dir: &std::path::Path, relative_path: &str) -> String {
        std::fs::read_to_string(manifest_dir.join(relative_path))
            .unwrap_or_else(|error| panic!("{relative_path} should be readable: {error}"))
    }
}
